name: flutter_ring_kit_example
description: Demonstrates how to use the flutter_ring_kit plugin.

publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: 1.0.2
  firebase_core: 1.12.0
  firebase_messaging: 11.2.6
  flutter:
    sdk: flutter
  flutter_ring_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2

flutter:
  uses-material-design: true
