name: flutter_ring_kit
description: A new flutter plugin project.
version: 0.0.1
# homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2

flutter:
  plugin:
    platforms:
      android:
        package: com.oryn.lotus.flutter_ring_kit
        pluginClass: FlutterRingKitPlugin
      ios:
        pluginClass: FlutterRingKitPlugin
