// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcqyAeKCeUhtweWBq8UAQBBO2v26LqWkk',
    appId: '1:1081752898559:android:abf4ab54b616425d47b5ca',
    messagingSenderId: '1081752898559',
    projectId: 'flutter-ring-kit',
    storageBucket: 'flutter-ring-kit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG0wdQyP91IErfR_wu0sRCGCs_92lbt7E',
    appId: '1:1081752898559:ios:5d06015064f1518447b5ca',
    messagingSenderId: '1081752898559',
    projectId: 'flutter-ring-kit',
    storageBucket: 'flutter-ring-kit.appspot.com',
    iosClientId:
        '1081752898559-dqkkf04u14eoeq78po5nuslgi7j6d37g.apps.googleusercontent.com',
    iosBundleId: 'com.oryn.lotus.flutterRingKitExample',
  );
}
